### ISSUE TITLE
stashDBTagImport: no tags are imported, 'Failed to create tag' errors

### ISSUE THREAD

**Issue by MCSmarties** [Serechops/Serechops-Stash#13]
Unfortunately I cannot get this plugin to work. It runs, but no tags are created. The log shows constant "Failed to create tag" errors.
(Your plugin "Bulk Import Performers" works just fine). Running Stash 0.26.2 on Windows 11, accessed via Firefox.

I am attaching the stash log, the anonymized database (less than a hundred scenes, was using it for testing purposes only) and a printout of the installed python modules. Do you have any idea what the problem might be? Thanks!

[python.log](https://github.com/user-attachments/files/16608808/python.log)
[Stashlog.log](https://github.com/user-attachments/files/16608813/Stashlog.log)
[stash-go.sqlite.anonymous.58.zip](https://github.com/user-attachments/files/16608815/stash-go.sqlite.anonymous.58.zip)

**Comment by Serechops** [comment]
I've been meaning to add API key support to all of my old scripts. In the script itself right near the bottom, ensure you have your URL set properly to point to your Stash server, 

Then, try disabling any credentials on your Stash, reload the Plugins and test it again :)

**Comment by makuc** [comment]
Has been fixed, if you properly configure URL and API key. Issue can be closed.

**Comment by Serechops** [comment]
In the latest release, you no longer have to configure the endpoint or API key. This should be taken care of automatically. Issue will be closed. Cheers!
