### ISSUE TITLE
[performerGallery] feature request - configurable download location

### ISSUE THREAD

**Issue by MyDirtyAccount** [Serechops/Serechops-Stash#27]
Thanks for this excellent plugin!

Downloading into the plugin's own directory isn't, IMNSHO, not ideal. Would you consider making the download location configurable?

**Comment by Serechops** [comment]
In `v1.2` this has been addressed. Cheers!

**Comment by MyDirtyAccount** [comment]
> In `v1.2` this has been addressed. Cheers!

You, sir, are a god among men. Thank you!
